export const openApiDocument = {
  openapi: '3.1.0',
  info: {
    title: 'Retail Lens API',
    version: '1.0.0',
    description: 'Backend APIs for optical retail operations',
  },
  servers: [{ url: '/api/v1' }],
  paths: {
    '/health': { get: { summary: 'Health check', responses: { '200': { description: 'OK' } } } },
    '/auth/login': { post: { summary: 'Login', responses: { '200': { description: 'Success' } } } },
    '/auth/refresh': { post: { summary: 'Refresh token', responses: { '200': { description: 'Success' } } } },
    '/job-cards/{id}/items/{itemId}': { delete: { summary: 'Remove job card item', responses: { '200': { description: 'Removed' } } } },
    '/job-cards/{id}/payments': { post: { summary: 'Record payment', responses: { '201': { description: 'Created' } } } },
    '/inventory': { get: { summary: 'List inventory', responses: { '200': { description: 'Success' } } }, post: { summary: 'Create inventory item', responses: { '201': { description: 'Created' } } } },
    '/inventory/{id}': { put: { summary: 'Update stock', responses: { '200': { description: 'Updated' } } } },
    '/inventory/{id}/history': { get: { summary: 'Inventory history', responses: { '200': { description: 'Success' } } } },
    '/inventory/alerts': { get: { summary: 'Inventory alerts', responses: { '200': { description: 'Success' } } } },
    '/tasks': { get: { summary: 'Task summary', responses: { '200': { description: 'Success' } } } },
    '/employees/{id}/tasks': { get: { summary: 'Employee task report', responses: { '200': { description: 'Success' } } } },
    '/reports/sales': { get: { summary: 'Sales report', responses: { '200': { description: 'Success' } } } },
    '/finances/daily-summary': { get: { summary: 'Daily finance summary', responses: { '200': { description: 'Success' } } } },
    '/finances/expenses': { post: { summary: 'Create expense', responses: { '201': { description: 'Created' } } } },
    '/finances/expenses/{id}': { put: { summary: 'Update expense', responses: { '200': { description: 'Updated' } } }, delete: { summary: 'Delete expense', responses: { '200': { description: 'Deleted' } } } },
    '/settings/store': { get: { summary: 'Get store settings', responses: { '200': { description: 'Success' } } }, put: { summary: 'Update store settings', responses: { '200': { description: 'Updated' } } } },
    '/notifications/send': { post: { summary: 'Queue notification', responses: { '202': { description: 'Queued' } } } },
    '/sync': { post: { summary: 'Sync offline actions', responses: { '202': { description: 'Accepted' } } } },
  },
} as const;
